# Generated by Django 5.1.7 on 2025-03-07 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('fecha_publicacion', models.DateField()),
                ('fecha_disposicion', models.DateField(blank=True, null=True)),
                ('titulo', models.TextField()),
                ('texto', models.TextField(blank=True, null=True)),
                ('url_pdf', models.URLField(blank=True, max_length=500, null=True)),
                ('url_xml', models.URLField(blank=True, max_length=500, null=True)),
                ('seccion', models.CharField(blank=True, max_length=10, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('pagina_inicial', models.IntegerField(blank=True, null=True)),
                ('pagina_final', models.IntegerField(blank=True, null=True)),
                ('vigencia_agotada', models.BooleanField(blank=True, null=True)),
                ('judicialmente_anulada', models.BooleanField(blank=True, null=True)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_documento', to='boe_analisis.departamento')),
                ('diario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_documento', to='boe_analisis.diario')),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Estado_consolidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Legislatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presidente', models.CharField(max_length=200)),
                ('inicio', models.DateField()),
                ('fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=4000, null=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Origen_legislativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=4000, null=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=4000, null=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=4000, null=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Tramitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=4000, null=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_documento', to='boe_analisis.documento')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='estado_consolidacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estados_consolidacion_documento', to='boe_analisis.estado_consolidacion'),
        ),
        migrations.AddField(
            model_name='documento',
            name='legislatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legislaturas_documento', to='boe_analisis.legislatura'),
        ),
        migrations.AddField(
            model_name='documento',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='materias_documento', to='boe_analisis.materia'),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_documento', to='boe_analisis.documento')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='origen_legislativo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origenes_legislativos_documento', to='boe_analisis.origen_legislativo'),
        ),
        migrations.AddField(
            model_name='legislatura',
            name='partido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boe_analisis.partido'),
        ),
        migrations.AddField(
            model_name='documento',
            name='rango',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rangos_documento', to='boe_analisis.rango'),
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_salientes_documento', to='boe_analisis.documento')),
                ('palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boe_analisis.palabra')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_entrantes_documento', to='boe_analisis.documento')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoAnuncio',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='boe_analisis.documento')),
                ('fecha_presentacion_ofertas', models.CharField(blank=True, max_length=4000, null=True)),
                ('fecha_apertura_ofertas', models.CharField(blank=True, max_length=4000, null=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('ambito_geografico', models.CharField(blank=True, max_length=4000, null=True)),
                ('materias_anuncio', models.CharField(blank=True, max_length=4000, null=True)),
                ('materias_cpv', models.CharField(blank=True, max_length=4000, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=4000, null=True)),
                ('modalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modalidades_documento', to='boe_analisis.modalidad')),
                ('precio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precios_documento', to='boe_analisis.precio')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_documento', to='boe_analisis.tipo')),
                ('tramitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramitaciones_documento', to='boe_analisis.tramitacion')),
            ],
            bases=('boe_analisis.documento',),
        ),
    ]
