# Generated by Django 5.1.7 on 2025-03-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boe_analisis', '0004_alter_alertausuario_id_alter_categoriaalerta_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaalerta',
            name='color',
            field=models.CharField(blank=True, help_text='Código de color en formato hexadecimal', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='categoriaalerta',
            name='palabras_clave',
            field=models.TextField(blank=True, help_text='Palabras clave separadas por comas', null=True),
        ),
    ]
