# Generated by Django 5.1.7 on 2025-03-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boe_analisis', '0005_categoriaalerta_color_categoriaalerta_palabras_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosimplificado',
            name='codigo_departamento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
