# Generated by Django 5.1.7 on 2025-03-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boe_analisis', '0006_documentosimplificado_codigo_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosimplificado',
            name='palabras_clave',
            field=models.TextField(blank=True, null=True),
        ),
    ]
